### PR TITLE
[6.3] Fix for proto files not being viewable in Perfetto UI (#16)

### PR DESCRIPTION
**Pull request by dgaliffiAMD**
- Fix for proto files not being viewable in Perfetto UI
  - Ported from https://github.com/ROCm/omnitrace/pull/411

- Update Workflows

- Use V47 trace_processor_shell for certain OS releases.
  - RedHat 8, SUSE 15.5, and Ubuntu 20.04 are no longer compatible with the latest trace_processor_shell.
  - Incompatible version of GLIBC.

- Remove notes about Perfetto workaround in documentation.

---------

### CODE REVIEW

**Comment by dgaliffiAMD** [comment]
Cherrypicking to release/rocm-rel-6.3

**Review by jrmadsen — APPROVED** [review]

**Review by njobypet — APPROVED** [review]

**Review by amd-jnovotny — APPROVED** [review]
Docs changes look good.

**Comment by gsitaram** [comment]
@dgaliffiAMD , I have been pointed to this PR for a fix regarding merging multiple proto files into one. I wonder if this has to be merged to `amd-staging`, then to `amd-mainline` and then to `rocm-release-6.3` branch. Please correct me if my understanding is wrong.

**Comment by dgaliffiAMD** [comment]
> @dgaliffiAMD , I have been pointed to this PR for a fix regarding merging multiple proto files into one. I wonder if this has to be merged to `amd-staging`, then to `amd-mainline`, and then to `rocm-release-6.3` branch. Please correct me if my understanding is wrong.

Hi @gsitaram, once a release branch has been created (branched from amd-mainline), it's pretty much in lock down mode. Individual changes can be cherry-picked and must be review by the @rocm/release-management team before they are approved and merged. 
This change has been approved, but we have to wait for a @rocm/release-management member to merge it to `release/rocm-rel-6.3`.

**Pull request merged**
